check if a given value of a specified property is unique within a data context.
fjalvingh/domui pull request #514
Opened 2023-11-28 12:55 UTC by milosilic

2023-11-28 13:07 UTC, millevlada approved these changes

2023-11-28 13:07 UTC, millevlada requested changes
build fails...
Error:  /home/runner/work/domui/domui/to.etc.domui/src/main/java/to/etc/domui/util/db/QCheckUtil.java:[37,1764] PropertyMetaModel is a raw type. References to generic type PropertyMetaModel<T> should be parameterized
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project to.etc.domui: Compilation failure

2023-11-28 13:09 UTC, millevlada commented on to.etc.domui/src/main/java/to/etc/domui/util/db/QCheckUtil.java
> +		PropertyMetaModel pmm = MetaManager.getPropertyMeta(clz, uniqueCheckProperty);
this should be PropertyMetaModel<V> pmm = ...
and then you do not need to have a cast too

2023-11-28 13:32 UTC, millevlada approved these changes

2023-11-29 13:04 UTC, fjalvingh approved these changes

2023-11-29 13:05 UTC, merged