method to set label before checkbox in CheckboxSetInputBase class
fjalvingh/domui pull request #557
Opened 2024-08-29 10:38 UTC by milosilic

﻿Ability to set the labels for each checkbox  on the left side of the toggle.
﻿The spacing between two filters and their belonging labels are made bigger so it is more clear which label refers to which toggle.

2024-08-29 13:21 UTC, millevlada commented on to.etc.domui/src/main/resources/resources/themes/scss/winter/_checkboxset.scss
> +		.ui-cbis-p label {
We want extra margin only when label is before checkbox, otherwise it would consume some unwanted space when it is used as after checkbox.
Add separate part of style (label-first) to mark that:
.ui-cbis-p {
  padding-right: 10px;
  &.label-first {
    display: flex;
    align-items: center;
    label {
      margin-right: 4px;
    }
  }
}

2024-08-29 13:21 UTC, millevlada commented on to.etc.domui/src/main/java/to/etc/domui/component/input/CheckboxSetInputBase.java
> +			pair.add(span);
add:
span.addCss("label-first");

2024-08-29 13:21 UTC, millevlada requested changes
see remarks

2024-08-30 13:51 UTC, millevlada approved these changes

2024-09-10 09:16 UTC, fjalvingh approved these changes

2024-09-10 09:16 UTC, fjalvingh commented on to.etc.domui/src/main/java/to/etc/domui/component/input/CheckboxSetInputBase.java
> +			span.addCssClass("label-first");
All css classes in DomUI use the ui-prefix combined with the component short code.

2024-09-10 09:16 UTC, merged